server:
  port: 8081
  servlet:
    context-path: /identity
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope: ${SCOPE}
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  application:
    name: identity-service
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signer-key: ${JWT_SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 10000
  issuer: DANGCHIEN

feign:
  client:
    config:
      profile-service:
        url: ${PROFILE_URL}
      vault-service:
        url: ${VAULT_URL}