server:
  port: 8084
  servlet:
    context-path: /vault
spring:
  application.name: vault-service
  data:
    mongodb:
      uri: ${URI_MONGODB}

TPBank:
  username: ${TPB_USERNAME}
  password: ${TPB_PASSWORD}
  accountNo: ${TPB_ACCOUNT}
