server:
  port: 8084
  servlet:
    context-path: /vault
spring:
  application.name: vault-service
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

vnPay:
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

TPBank:
  username: ${TPB_USERNAME}
  password: ${TPB_PASSWORD}
  accountNo: ${TPB_ACCOUNT}
